### ISSUE TITLE
'TypeError: element_roll.click() is not a function'

### ISSUE THREAD

**Issue by AlexMagicPro** [renowator/CryptosFaucets_Bot#14]
after solving the sandbox issue the bot started correctly and everything went ok. properly rewarded. from the second time it gives me this error:
`'TypeError: element_roll.click() is not a function'`
 what can it be? my fear is that he can't find the roll button. has it ever happened to you?

**Comment by renowator** [comment]
That might be because of something on the website. Sometimes popups can appear, or it is blocked. This happens to me pretty often.

**Comment by noahbassirat** [comment]
Hi I have a Mac Air 2017 running BigSUR and I really wanna use this but I can't get it to work. I think I'm getting a little confused as to where I'm supposed to type in [cp env.sample .env] or maybe how to fill in my email and password in those areas. it could also be that I don't know how to use nsjw because at first, I thought I was supposed to drag the .zip or master folder into the app interface but that just gave me a directory so I typed it in terminal as: [cp EMAIL=(insert my email) PASS=(insert my password) .env] and this [usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory) would come up but after I typed in [node console_bot.js] it would just give me this [internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Users/noahbassirat/console_bot.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}]
I haven't signed up to all the sites with your ref code yet but I was going to do it after I got it to work, and I doubt that has anything to do with my issue

I'd really appreciate it if you guys could help me out and I know I'm submitting this in the wrong place but I never use GitbHub so I don't know how else I could've gotten in contact with you. Thank you.

P.S. Another random little note is that in env.sample you guys put "monemail" and "monpwd" which is fine for me cuz I speak french but maybe some stupid people wanna use the bot btu don't know what mon means will get confused. Or maybe this would be too hard for stupid people anyways.

**Comment by umarm6** [comment]
they have add recaptcha :(
